-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE Veiculo (
id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
modelo VARCHAR(255) NOT NULL,
marca VARCHAR(255) NOT NULL,
cambio VARCHAR(255),
combustivel VARCHAR(20) NOT NULL,
cor VARCHAR(100) NOT NULL,
versao VARCHAR(255),
preco DECIMAL(11, 2) NOT NULL,
finalPlaca CHAR(3),
tipo VARCHAR(5) NOT NULL,
kilometragem VARCHAR(255) NOT NULL,
numPortas CHAR(1),
detalhes VARCHAR(8000),
ano VARCHAR(20) NOT NULL,
chassi CHAR(17) NOT NULL UNIQUE
)

CREATE TABLE Cliente (
id INT AUTO_INCREMENT PRIMARY KEY,
id_login INT NOT NULL UNIQUE,
tipo VARCHAR(10)
)

CREATE TABLE Reservar (
id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
id_veiculo INT NOT NULL,
id_reservar INT NOT NULL,
dataRegistro DATETIME NOT NULL,
dataReserva DATETIME NOT NULL,
FOREIGN KEY(id_veiculo) REFERENCES Veiculo (id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(id_reservar) REFERENCES Cliente (id)
)

CREATE TABLE Login (
id INT AUTO_INCREMENT PRIMARY KEY,
usuario VARCHAR(255) NOT NULL UNIQUE,
senha VARCHAR(255) NOT NULL
)

CREATE TABLE Endereco (
id INT AUTO_INCREMENT PRIMARY KEY,
id_cliente INT NOT NULL,
logradouro VARCHAR(255) NOT NULL,
complemento VARCHAR(255),
cep CHAR(8) NOT NULL,
pais VARCHAR(100) NOT NULL,
cidade VARCHAR(255) NOT NULL,
bairro VARCHAR(255) NOT NULL,
numero VARCHAR(15) NOT NULL,
tipoEndereco VARCHAR(10) NOT NULL,
estado CHAR(2) NOT NULL,
FOREIGN KEY(id_cliente) REFERENCES Cliente (id) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE Email (
id INT AUTO_INCREMENT PRIMARY KEY,
id_cliente INT NOT NULL,
email VARCHAR(255) NOT NULL,
tipoEmail VARCHAR(10) NOT NULL,
FOREIGN KEY(id_cliente) REFERENCES Cliente (id) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE Telefone (
id INT AUTO_INCREMENT PRIMARY KEY,
id_cliente INT NOT NULL,
ddd CHAR(2) NOT NULL,
ddi CHAR(4) NOT NULL,
numero VARCHAR(25) NOT NULL,
tipoTelefone VARCHAR(10) NOT NULL,
FOREIGN KEY(id_cliente) REFERENCES Cliente (id) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE Juridico (
id_cliente INT NOT NULL,
nomeFantasia VARCHAR(255) NOT NULL UNIQUE,
razaoSocial VARCHAR(255) NOT NULL UNIQUE,
cnpj CHAR(15) NOT NULL UNIQUE,
ie CHAR(12),
im CHAR(10),
FOREIGN KEY(id_cliente) REFERENCES Cliente (id)
)

CREATE TABLE Fisico (
id_cliente INT NOT NULL,
nome VARCHAR(255) NOT NULL,
cpf CHAR(11) NOT NULL UNIQUE,
rg VARCHAR(20),
FOREIGN KEY(id_cliente) REFERENCES Cliente (id)
)

ALTER TABLE Cliente ADD FOREIGN KEY(id_login) REFERENCES Login (id) ON UPDATE CASCADE ON DELETE CASCADE
