USE URBANO;

ALTER TABLE RESERVAR DROP FOREIGN KEY fk_reserva_veiculo;
ALTER TABLE RESERVAR DROP FOREIGN KEY fk_reserva_cliente;
DROP TABLE RESERVAR;
DROP TABLE VEICULO;

ALTER TABLE ENDERECO DROP FOREIGN KEY fk_enderecos;
DROP TABLE ENDERECO;

ALTER TABLE TELEFONE DROP FOREIGN KEY fk_telefones;
DROP TABLE TELEFONE;

ALTER TABLE EMAIL DROP FOREIGN KEY fk_emails;
DROP TABLE EMAIL;

ALTER TABLE JURIDICO DROP FOREIGN KEY fk_cliente_juridico;
DROP TABLE JURIDICO;

ALTER TABLE FISICO DROP FOREIGN KEY fk_cliente_fisico;
DROP TABLE FISICO;

ALTER TABLE CLIENTE DROP FOREIGN KEY fk_login;
DROP TABLE CLIENTE;

DROP TABLE LOGIN;